

version: '3.8'
services:
  python3:
    restart: always
    build: .
    container_name: 'app'
    working_dir: '/root/'
    tty: true
    volumes:
      - .:/root/.
      - staticdata:/var/www/app/static/
    ports:
      - "8000:8000"
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: asw20231106
      MYSQL_DATABASE: accounts
      MYSQL_USER: kanamehirata
      MYSQL_PASSWORD: asw20231106
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  staticdata: