# Generated by Django 4.2.7 on 2023-12-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=True, max_length=10, verbose_name='username'),
        ),
    ]
