# Generated by Django 4.2.7 on 2023-12-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
