# Generated by Django 4.2.7 on 2023-12-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
