# Generated by Django 4.2.7 on 2023-12-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
