# Generated by Django 4.2.7 on 2023-12-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
